# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-tuto',
                'doc_host': 'https://jeannotlapin.github.io',
                'git_url': 'https://github.com/jeannotlapin/nbdev-tuto',
                'lib_path': 'nbdev_tuto'},
  'syms': {'nbdev_tuto.core': {'nbdev_tuto.core.foo': ('core.html#foo', 'nbdev_tuto/core.py')}}}
